import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ngc_revision import revision_lines
#!/usr/bin/env python3
"""Generate the plywood hold-down program: counterbore + through hole, 12 places.

Literal coordinates on purpose. A parametric version cannot be checked -- the
linter cannot evaluate a named parameter, so every G3 reads as a zero-radius arc
and the arc check, which is the one that catches a real abort, is dead.

    tools/gen_plywood_tnut.py > plywood_tnut_12.ngc
"""
TOOL_NO = 6             # T6, the 1/2 in endmill -- checked against #5400 at runtime
COLS  = [0.0, 559.6, 1119.2]                    # C1 C2 C3, 1119.2 total span
ROWS  = [0.0, 316.725, 567.450, 817.175]        # R1 at the datum, counting up
TOOL  = 12.700          # 1/2 in
CB_D, CB_Z = 26.670, 12.700     # 1.05 in dia, 0.5 in deep
TH_D, TH_Z = 15.240, 19.050     # 0.6 in dia, exactly 3/4 in deep -- flush with the bottom face
STEP  = 6.350           # 0.25 in per depth pass
PLANE = 12.700          # rapid, feed and clearance planes: 0.5 in above Z0
RPM, FEED = 9000, 1200.0

r1 = (CB_D - TOOL) / 2.0
r2 = (TH_D - TOOL) / 2.0

def passes(z_from, z_to):
    z, out = z_from, []
    while z > z_to + 1e-9:
        z = max(z - STEP, z_to)
        out.append(round(z, 4))
    return out

L = ["%",
     "(plywood_tnut_12 - 12 hold-down holes, 3 columns x 4 rows)",
     "(GENERATED by ned:tools/gen_plywood_tnut.py -- edit the generator, not this file)",
     "(Z0 IS THE PLYWOOD TOP, set by the operator with the cutter already in the holder.)",
     "(Datum is the bottom-left hole: R1 C1 = X0 Y0. Everything runs +X and +Y.)",
     "(Columns X 0 / 559.6 / 1119.2 -- 1119.2 span, the same as the bed's four bolt holes.)",
     "(Rows Y 0 / 316.725 / 567.45 / 817.175 -- the bed's own uneven slot pitch.)",
     "(Counterbore %.3f dia to Z-%.3f, orbit radius %.3f.)" % (CB_D, CB_Z, r1),
     "(Through %.3f dia to Z-%.3f, orbit radius %.3f.)" % (TH_D, TH_Z, r2),
     "(Cutter %.3f = 1/2 in. Rapid, feed and clearance planes all Z+%.3f.)" % (TOOL, PLANE),
     "(Speeds are the ini defaults: DEFAULT_SPINDLE_SPEED and DEFAULT_LINEAR_VELOCITY.)",
     "",
     "G21 G90 G17 G94 G40 G49 G54",
     "",
     "(No tool change and no G43 here. Z0 is the plywood top, touched off)",
     "(with this cutter already in the holder. So the file refuses to run)",
     "(unless the right cutter is actually in the spindle.)",
     "o100 if [#5400 NE %d]" % TOOL_NO,
     "  (abort, PLYWOOD TNUT: T%d is not in the spindle - load it and declare it first)" % TOOL_NO,
     "o100 endif",
     "o101 if [ABS[#5410 - %.4f] GT 0.01]" % TOOL,
     "  (abort, PLYWOOD TNUT: the tool in the spindle is not %.3f mm - check the tool table DIAMETER)" % TOOL,
     "o101 endif",
     "",
     "(THE TOOL LENGTH MUST BE IN FORCE. #5401-#5409 are the APPLIED offsets,)",
     "(set by the G43 family and zeroed by G49. #5403 EQ 0 means the machine)",
     "(is positioning the SPINDLE NOSE, not the tip, and Z0 was touched off)",
     "(with the tip -- every move would run one whole tool length deeper.)",
     "(Loading a program RESETS the interpreter, which re-runs the ini's)",
     "(RS274NGC_STARTUP_CODE, and that line contains G49. 2026-09-29.)",
     "o102 if [ABS[#5403] LT 0.001]",
     "  (abort, PLYWOOD TNUT: no tool length is applied - G49 is in force so Z0 is the spindle nose and the tip would run one tool length deeper - press G43, re-check your Z zero, then run)",
     "o102 endif",
     "",
     "(MACHINE Z0 FIRST, THEN THE START XY, THEN ANYTHING ELSE. Operator)",
     "(2026-09-29: 'EVERY FUCKING FILE we run must have that check'. G53 Z0 is)",
     "(the top of Z travel and the only retract whose safety does not depend)",
     "(on a work offset -- and the offset is exactly what goes wrong.)",
     "G53 G0 Z0",
     "G0 X%.4f Y%.4f" % (COLS[0], ROWS[0]),
     "G0 Z%.4f" % PLANE,
     ""]

n = 0
for ri, y in enumerate(ROWS):
    for ci, x in enumerate(COLS):
        n += 1
        L.append("(hole %d of 12 -- R%d C%d)" % (n, ri + 1, ci + 1))
        L.append("G0 X%.4f Y%.4f" % (x, y))
        if n == 1:
            L.append("M3 S%d" % RPM)
            L.append("G4 P3.0")
        L.append("G0 Z%.4f" % PLANE)
        for z in passes(0.0, -CB_Z):                      # counterbore
            L.append("G1 Z%.4f F%.1f" % (z, FEED))
            L.append("G1 X%.4f F%.1f" % (x + r1, FEED))
            L.append("G3 X%.4f Y%.4f I%.4f J0.0" % (x + r1, y, -r1))
            L.append("G1 X%.4f F%.1f" % (x, FEED))
        for z in passes(-CB_Z, -TH_Z):                    # through
            L.append("G1 Z%.4f F%.1f" % (z, FEED))
            L.append("G1 X%.4f F%.1f" % (x + r2, FEED))
            L.append("G3 X%.4f Y%.4f I%.4f J0.0" % (x + r2, y, -r2))
            L.append("G1 X%.4f F%.1f" % (x, FEED))
        L.append("G0 Z%.4f" % PLANE)
        L.append("")

L += ["M5", "G0 Z%.4f" % PLANE, "M30", "%"]
# RULE 3.7: the revision header goes on top, and its md5 is of everything
# below it -- computed last, inserted first.
CHANGED = ("G53 G0 Z0 before the start XY; aborts when no tool length "
           "is applied")
_hdr = revision_lines(L[1:], 'gen_plywood_tnut.py', CHANGED)
print("\n".join([L[0]] + _hdr + L[1:]))
