#!/usr/bin/env python3
"""Generate the bed facing program for ned.

    tools/gen_facing.py > /home/brains/linuxcnc/nc_files/setup/face_bed.ngc

FILE SHAPE, operator 2026-09-29: "i want it to follow all the rules, have
parameters i can set right away second, and a clear description of the code
after that before the code body."  So: title, PARAMETERS, DESCRIPTION, body.

THE CONFIDENCE LAP, operator 2026-09-29: "THE FIRST THING YOU DO IS TO MOVE
ALONG THE OUTER PATH AT Z5. THIS GIVES ME CONFIDENCE THAT I AM FACING
EVERYTHING BEFORE IT THEN PROCEEDS TO THE FACING."  One lap of the rectangle
at Z5, cutting nothing, before anything goes down.
"""
import math

# ---- the numbers the operator sets -----------------------------------------
# THE TOOL CENTRE PATH, not the cut boundary. Operator 2026-09-29: 'TOOL
# CENTER FROM Y = 0 TO 1500 WILL DO'. The cutter EDGE therefore overhangs
# by one radius on every side, so the swept surface is R bigger all round.
CENTRE_X    = 2570.0   # mm, centre travels X0 -> X2570. 4043.725 available
CENTRE_Y    = 1500.0   # mm, centre travels Y0 -> Y1500. 1788.000 available
TOOL        = 1        # T1, the 3 in face mill
TOOL_DIA    = 76.2     # mm, must match the tool table DIAMETER
OVERLAP     = 12.7     # mm, 0.5 in. Operator 2026-09-29: '.5in overlap
                       # should do'. STEPOVER is derived: dia - overlap
SPINDLE_RPM = 5000     # operator 2026-09-29: 'LETS RUN IT AT 5000 rpm.
                       # that should be plenty for this 3in face mill.'
                       # Vc = pi * 76.2 * 5000 / 1000 = 1197 m/min
FEED        = 6000.0   # mm/min = 0.200 mm/tooth at 6 flutes and 5000 rpm.
                       # DERIVED from the rpm to hold the chip load -- raising
                       # S without F would have thinned it to 0.160
PLUNGE_FEED = 600.0    # mm/min, the helix
Z_RAPID     = 10.0     # mm, the height every rapid runs at
Z_LAP       = 5.0      # mm, the confidence lap
Z_FACE      = 0.0      # mm, the finished surface. The operator zeroes here
HELIX_DIA   = 76.2     # mm, 3 in, one cutter diameter
DWELL       = 3.0      # s, spindle settle before the first move

R = TOOL_DIA / 2.0
STEP = TOOL_DIA - OVERLAP
L = []
def w(s=''):
    L.append(s)

w('%')
w('(FACE BED -- %s x %s mm, T%d %s mm face mill)'
  % (f'{CENTRE_X:.1f}', f'{CENTRE_Y:.1f}', TOOL, f'{TOOL_DIA:.1f}'))
w('(GENERATED by ned:tools/gen_facing.py -- edit the generator, not this file)')
w()
w('(=== PARAMETERS -- set these before you run ============================)')
w('(  Change a number here and nothing else. Every move below is built from)')
w('(  these, so the file stays true to whatever you set.)')
w('#<centre_x>   = %.4f   (mm, the TOOL CENTRE runs X0 to here. 4043.725 of travel)' % CENTRE_X)
w('#<centre_y>   = %.4f   (mm, the TOOL CENTRE runs Y0 to here. 1788.000 -- the tight one)' % CENTRE_Y)
w('#<tool>       = %d        (T%d, the 3 in face mill)' % (TOOL, TOOL))
w('#<tool_dia>   = %.4f     (mm, must match the tool table DIAMETER)' % TOOL_DIA)
w('#<stepover>   = %.4f     (mm, = dia %.1f minus %.1f overlap)' % (STEP, TOOL_DIA, OVERLAP))
w('#<rpm>        = %d        (Vc = pi x dia x rpm / 1000 = %.0f m/min)'
  % (SPINDLE_RPM, math.pi * TOOL_DIA * SPINDLE_RPM / 1000.0))
w('#<feed>       = %.4f   (mm/min, %.4f mm/tooth at 6 flutes)'
  % (FEED, FEED / (SPINDLE_RPM * 6.0)))
w('#<plunge>     = %.4f    (mm/min, the helix)' % PLUNGE_FEED)
w('#<z_rapid>    = %.4f     (mm, every rapid runs at this height)' % Z_RAPID)
w('#<z_lap>      = %.4f      (mm, the confidence lap -- cuts nothing)' % Z_LAP)
w('#<z_face>     = %.4f      (mm, the finished surface. You zero here)' % Z_FACE)
w('#<helix_dia>  = %.4f     (mm, 3 in, one cutter diameter)' % HELIX_DIA)
w('#<dwell>      = %.4f      (s, spindle settle before the first move)' % DWELL)
w()
w('(=== DESCRIPTION -- what this does, in order ===========================)')
w('(  Z0 IS THE FINISHED SURFACE. You touch off on where you want the bed)')
w('(  to END UP, with T%d already in the holder. The program never asks how)' % TOOL)
w('(  much stock is above that -- it faces to Z0 and stops.)')
w('( )')
w('(  X0 Y0 is where the TOOL CENTRE starts. It runs to X%s Y%s. The edge)'
  % (f'{CENTRE_X:.1f}', f'{CENTRE_Y:.1f}'))
w('(  overhangs %.4f all round, so the surface actually swept is)' % R)
w('(  X%.4f to X%.4f by Y%.4f to Y%.4f.)'
  % (-R, CENTRE_X + R, -R, CENTRE_Y + R))
w('( )')
w('(  1. REFUSE unless T%d is actually in the spindle and its diameter)' % TOOL)
w('(     matches. Z0 means nothing if a different cutter touched it off.)')
w('(  2. MACHINE Z0 first, then the start XY, then down to Z%s. Spindle)'
  % f'{Z_RAPID:.1f}')
w('(     on, %d rpm, %s s settle.)' % (SPINDLE_RPM, f'{DWELL:.0f}'))
w('(  3. THE CONFIDENCE LAP. One full circuit of the rectangle at Z%s,)' % f'{Z_LAP:.1f}')
w('(     cutting nothing, so you can watch the whole boundary go past before)')
w('(     anything descends. Operator 2026-09-29: "THIS GIVES ME CONFIDENCE)')
w('(     THAT I AM FACING EVERYTHING BEFORE IT THEN PROCEEDS TO THE FACING".)')
w('(     The lap traces the CUTTER CENTRE path -- X0 Y0 to X%s Y%s --)'
  % (f'{CENTRE_X:.1f}', f'{CENTRE_Y:.1f}'))
w('(     so the cutter EDGE runs %.4f outside it on every side.)' % R)
w('(  4. Helical entry, %s mm diameter, from Z%s down to Z%s. A ramp, not a)'
  % (f'{HELIX_DIA:.1f}', f'{Z_LAP:.1f}', f'{Z_FACE:.1f}'))
w('(     plunge -- a %s mm face mill has no centre cutting edge.)' % f'{TOOL_DIA:.1f}')
w('(  5. Raster along X, stepping over %.4f in Y. Along the LONG side, so)' % STEP)
w('(     there are as few direction changes as possible.)')
w('(  6. Spindle off, Z clear. It does not return anywhere -- you decide.)')
w()
w('(=== BODY ==============================================================)')
w('(Every move below reads the PARAMETERS block. Nothing here is a literal)')
w('(that duplicates a number up there -- change it once, at the top, and the)')
w('(whole program follows. On 2026-09-29 the first version of this file had)')
w('(a parameter block over a body of literals: the operator changed centre_x)')
w('(to 2570 and the machine would still have run 2470. A parameter that does)')
w('(not drive anything is worse than none -- it reads as a guarantee.)')
w('G21 G90 G17 G94 G40 G49 G54')
w('G64 P0.05 Q0.05')
w()
w('(No tool change and no G43. Z0 was touched off with this cutter already)')
w('(in the holder, so the file refuses unless that is still true.)')
w('o100 if [#5400 NE #<tool>]')
w('  (abort, FACE BED: that tool is not in the spindle - load it and declare it first)')
w('o100 endif')
w('o101 if [ABS[#5410 - #<tool_dia>] GT 0.01]')
w('  (abort, FACE BED: the tool in the spindle is not the diameter this file expects - check the tool table DIAMETER)')
w('o101 endif')
w()
w('(THE TOOL LENGTH MUST BE IN FORCE. #5401-#5409 are the APPLIED offsets --)')
w('(set by the G43 family, zeroed by G49 -- so #5403 EQ 0 means the machine)')
w('(is positioning the SPINDLE NOSE, not the tip. Z0 was touched off with)')
w('(the tip, so every move would run one whole tool length deeper.)')
w('(2026-09-29: LOADING A PROGRAM RESETS THE INTERPRETER, which re-runs)')
w('(RS274NGC_STARTUP_CODE, and that line contains G49. So opening this file)')
w('(after touching off silently drops the offset, and the DRO still reads a)')
w('(plausible number. Nothing else on this machine catches it.)')
w('o102 if [ABS[#5403] LT 0.001]')
w('  (abort, FACE BED: no tool length is applied - G49 is in force so Z0 is the spindle nose and the tip would run one tool length deeper - press G43, re-check your Z zero, then run)')
w('o102 endif')
w()
w('(THE TOOL CENTRE PATH. Not inset -- these ARE the parameters above. The)')
w('(cutter EDGE overhangs by one radius on every side.)')
w('#<x0> = 0.0000')
w('#<y0> = 0.0000')
w('#<x1> = #<centre_x>')
w('#<y1> = #<centre_y>')
w('o103 if [[#<x1> LE #<x0>] OR [#<y1> LE #<y0>]]')
w('  (abort, FACE BED: centre_x and centre_y must both be greater than zero)')
w('o103 endif')
w('o104 if [#<stepover> LE 0]')
w('  (abort, FACE BED: stepover must be greater than zero)')
w('o104 endif')
w()
w('(MACHINE Z0 FIRST, THEN THE START XY, THEN ANYTHING ELSE. Operator)')
w('(2026-09-29: "whenever going to start of path. it MUST always, go to)')
w('(mscZ0, go to start XY. then do wahtever after that". G53 Z0 is the top)')
w('(of Z travel and is the ONE height where no XY move can strike anything)')
w('(-- a work-frame retract is only as safe as the offset it is measured)')
w('(from, and that offset is exactly what goes wrong.)')
w('G53 G0 Z0')
w('G0 X#<x0> Y#<y0>')
w('(RULE 6.3: THE SPINDLE STARTS HERE, AT THE XY RESUME, AND THE DESCENT)')
w('(COMES AFTER THE DWELL. I had the Z rapid above the M3 and the operator)')
w('(caught it: "did you break the spindle spinup rule as well". A cutter)')
w('(that spins up while already down is a cutter spinning in the work.)')
w('M3 S#<rpm>')
w('G4 P#<dwell>')
w('G0 Z#<z_rapid>')
w()
w('(--- 3. THE CONFIDENCE LAP. Cuts nothing. Watch the whole boundary. ---)')
w('G0 Z#<z_lap>')
w('G1 X#<x1> Y#<y0> F#<feed>')
w('G1 X#<x1> Y#<y1>')
w('G1 X#<x0> Y#<y1>')
w('G1 X#<x0> Y#<y0>')
w()
w('(--- 4. helical entry, z_lap down to z_face ---)')
w('(A ramp, not a plunge: a face mill has no centre cutting edge. The helix)')
w('(sits inside the boundary so it cuts no more than the raster will.)')
w('#<hr> = [#<helix_dia> / 2.0]')
w('#<hx> = [#<x0> + #<hr>]')
w('#<hz> = #<z_lap>')
w('#<hstep> = [[#<z_lap> - #<z_face>] / 3.0]')
w('G0 X#<hx> Y#<y0>')
w('o110 while [#<hz> GT #<z_face>]')
w('  #<hz> = [#<hz> - #<hstep>]')
w('  o111 if [#<hz> LT #<z_face>]')
w('    #<hz> = #<z_face>')
w('  o111 endif')
w('  G3 X#<hx> Y#<y0> I-#<hr> J0.0 Z#<hz> F#<plunge>')
w('o110 endwhile')
w('(one flat turn to clean the ramp out of the floor)')
w('G3 X#<hx> Y#<y0> I-#<hr> J0.0 F#<feed>')
w('G1 X#<x0> Y#<y0> F#<feed>')
w()
w('(--- 5. raster along X, stepping in Y. The loop reads #<stepover>, so)')
w('(    changing the overlap at the top changes the pass count here.)')
w('#<yy>   = #<y0>')
w('#<dir>  = 1')
w('#<more> = 1')
w('o120 while [#<more> GT 0]')
w('  o121 if [#<dir> GT 0]')
w('    G1 X#<x1> Y#<yy> F#<feed>')
w('  o121 else')
w('    G1 X#<x0> Y#<yy> F#<feed>')
w('  o121 endif')
w('  #<dir> = [0 - #<dir>]')
w('  o122 if [#<yy> GE #<y1>]')
w('    #<more> = 0')
w('  o122 else')
w('    #<yy> = [#<yy> + #<stepover>]')
w('    o123 if [#<yy> GT #<y1>]')
w('      #<yy> = #<y1>')
w('    o123 endif')
w('    G1 Y#<yy>')
w('  o122 endif')
w('o120 endwhile')
w()
w('(--- 6. done ---)')
w('M5')
w('G0 Z#<z_rapid>')
w('M30')
w('%')
print('\n'.join(L))
