#!/usr/bin/env python3
"""Generate the bed facing program for ned.

    tools/gen_facing.py > /home/brains/linuxcnc/nc_files/setup/face_bed.ngc

FILE SHAPE, operator 2026-09-29: "i want it to follow all the rules, have
parameters i can set right away second, and a clear description of the code
after that before the code body."  So: title, PARAMETERS, DESCRIPTION, body.

THE CONFIDENCE LAP, operator 2026-09-29: "THE FIRST THING YOU DO IS TO MOVE
ALONG THE OUTER PATH AT Z5. THIS GIVES ME CONFIDENCE THAT I AM FACING
EVERYTHING BEFORE IT THEN PROCEEDS TO THE FACING."  One lap of the rectangle
at Z5, cutting nothing, before anything goes down.
"""
import math

# ---- the numbers the operator sets -----------------------------------------
# THE TOOL CENTRE PATH, not the cut boundary. Operator 2026-09-29: 'TOOL
# CENTER FROM Y = 0 TO 1500 WILL DO'. The cutter EDGE therefore overhangs
# by one radius on every side, so the swept surface is R bigger all round.
CENTRE_X    = 2470.0   # mm, centre travels X0 -> X2470. 4043.725 available
CENTRE_Y    = 1500.0   # mm, centre travels Y0 -> Y1500. 1788.000 available
TOOL        = 1        # T1, the 3 in face mill
TOOL_DIA    = 76.2     # mm, must match the tool table DIAMETER
STEPOVER_PC = 70.0     # % of the cutter
SPINDLE_RPM = 4000     # Vc = pi * 76.2 * 4000 / 1000 = 957 m/min
FEED        = 4800.0   # mm/min = 0.200 mm/tooth at 6 flutes and 4000 rpm
PLUNGE_FEED = 600.0    # mm/min, the helix
Z_RAPID     = 10.0     # mm, the height every rapid runs at
Z_LAP       = 5.0      # mm, the confidence lap
Z_FACE      = 0.0      # mm, the finished surface. The operator zeroes here
HELIX_DIA   = 76.2     # mm, 3 in, one cutter diameter
DWELL       = 3.0      # s, spindle settle before the first move

R = TOOL_DIA / 2.0
STEP = TOOL_DIA * STEPOVER_PC / 100.0
L = []
def w(s=''):
    L.append(s)

w('%')
w('(FACE BED -- %s x %s mm, T%d %s mm face mill)'
  % (f'{CENTRE_X:.1f}', f'{CENTRE_Y:.1f}', TOOL, f'{TOOL_DIA:.1f}'))
w('(GENERATED by ned:tools/gen_facing.py -- edit the generator, not this file)')
w()
w('(=== PARAMETERS -- set these before you run ============================)')
w('(  Change a number here and nothing else. Every move below is built from)')
w('(  these, so the file stays true to whatever you set.)')
w('#<centre_x>   = %.4f   (mm, the TOOL CENTRE runs X0 to here. 4043.725 of travel)' % CENTRE_X)
w('#<centre_y>   = %.4f   (mm, the TOOL CENTRE runs Y0 to here. 1788.000 -- the tight one)' % CENTRE_Y)
w('#<tool>       = %d        (T%d, the 3 in face mill)' % (TOOL, TOOL))
w('#<tool_dia>   = %.4f     (mm, must match the tool table DIAMETER)' % TOOL_DIA)
w('#<stepover>   = %.4f     (mm, %.0f percent of the cutter)' % (STEP, STEPOVER_PC))
w('#<rpm>        = %d        (Vc = pi x dia x rpm / 1000 = %.0f m/min)'
  % (SPINDLE_RPM, math.pi * TOOL_DIA * SPINDLE_RPM / 1000.0))
w('#<feed>       = %.4f   (mm/min, %.4f mm/tooth at 6 flutes)'
  % (FEED, FEED / (SPINDLE_RPM * 6.0)))
w('#<plunge>     = %.4f    (mm/min, the helix)' % PLUNGE_FEED)
w('#<z_rapid>    = %.4f     (mm, every rapid runs at this height)' % Z_RAPID)
w('#<z_lap>      = %.4f      (mm, the confidence lap -- cuts nothing)' % Z_LAP)
w('#<z_face>     = %.4f      (mm, the finished surface. You zero here)' % Z_FACE)
w('#<helix_dia>  = %.4f     (mm, 3 in, one cutter diameter)' % HELIX_DIA)
w('#<dwell>      = %.4f      (s, spindle settle before the first move)' % DWELL)
w()
w('(=== DESCRIPTION -- what this does, in order ===========================)')
w('(  Z0 IS THE FINISHED SURFACE. You touch off on where you want the bed)')
w('(  to END UP, with T%d already in the holder. The program never asks how)' % TOOL)
w('(  much stock is above that -- it faces to Z0 and stops.)')
w('( )')
w('(  X0 Y0 is where the TOOL CENTRE starts. It runs to X%s Y%s. The edge)'
  % (f'{CENTRE_X:.1f}', f'{CENTRE_Y:.1f}'))
w('(  overhangs %.4f all round, so the surface actually swept is)' % R)
w('(  X%.4f to X%.4f by Y%.4f to Y%.4f.)'
  % (-R, CENTRE_X + R, -R, CENTRE_Y + R))
w('( )')
w('(  1. REFUSE unless T%d is actually in the spindle and its diameter)' % TOOL)
w('(     matches. Z0 means nothing if a different cutter touched it off.)')
w('(  2. Spindle on, %d rpm, %s s settle.)' % (SPINDLE_RPM, f'{DWELL:.0f}'))
w('(  3. THE CONFIDENCE LAP. One full circuit of the rectangle at Z%s,)' % f'{Z_LAP:.1f}')
w('(     cutting nothing, so you can watch the whole boundary go past before)')
w('(     anything descends. Operator 2026-09-29: "THIS GIVES ME CONFIDENCE)')
w('(     THAT I AM FACING EVERYTHING BEFORE IT THEN PROCEEDS TO THE FACING".)')
w('(     The lap traces the CUTTER CENTRE path -- X0 Y0 to X%s Y%s --)'
  % (f'{CENTRE_X:.1f}', f'{CENTRE_Y:.1f}'))
w('(     so the cutter EDGE runs %.4f outside it on every side.)' % R)
w('(  4. Helical entry, %s mm diameter, from Z%s down to Z%s. A ramp, not a)'
  % (f'{HELIX_DIA:.1f}', f'{Z_LAP:.1f}', f'{Z_FACE:.1f}'))
w('(     plunge -- a %s mm face mill has no centre cutting edge.)' % f'{TOOL_DIA:.1f}')
w('(  5. Raster along X, stepping over %.4f in Y. Along the LONG side, so)' % STEP)
w('(     there are as few direction changes as possible.)')
w('(  6. Spindle off, Z clear. It does not return anywhere -- you decide.)')
w()
w('(=== BODY ==============================================================)')
w('G21 G90 G17 G94 G40 G49 G54')
w('G64 P0.05 Q0.05')
w()
w('(No tool change and no G43. Z0 was touched off with this cutter already)')
w('(in the holder, so the file refuses unless that is still true.)')
w('o100 if [#5400 NE %d]' % TOOL)
w('  (abort, FACE BED: T%d is not in the spindle - load it and declare it first)' % TOOL)
w('o100 endif')
w('o101 if [ABS[#5410 - %.4f] GT 0.01]' % TOOL_DIA)
w('  (abort, FACE BED: the tool in the spindle is not %.3f mm - check the tool table DIAMETER)' % TOOL_DIA)
w('o101 endif')
w()
w('(THE TOOL CENTRE PATH. Not inset -- these ARE the numbers above. The)')
w('(cutter EDGE overhangs by the radius %.4f on every side.)' % R)
w('#<x0> = 0.0000')
w('#<y0> = 0.0000')
w('#<x1> = %.4f' % CENTRE_X)
w('#<y1> = %.4f' % CENTRE_Y)
w('o102 if [[#<x1> LT #<x0>] OR [#<y1> LT #<y0>]]')
w('  (abort, FACE BED: the rectangle is smaller than the cutter - nothing to face)')
w('o102 endif')
w()
w('G0 Z%.4f' % Z_RAPID)
w('G0 X#<x0> Y#<y0>')
w('M3 S%d' % SPINDLE_RPM)
w('G4 P%.4f' % DWELL)
w()
w('(--- 3. THE CONFIDENCE LAP at Z%.1f. Cuts nothing. Watch the boundary. ---)' % Z_LAP)
w('G0 Z%.4f' % Z_LAP)
w('G1 X#<x1> Y#<y0> F%.4f' % FEED)
w('G1 X#<x1> Y#<y1>')
w('G1 X#<x0> Y#<y1>')
w('G1 X#<x0> Y#<y0>')
w()
w('(--- 4. helical entry, %.1f mm diameter, Z%.1f down to Z%.1f ---)'
  % (HELIX_DIA, Z_LAP, Z_FACE))
w('(The helix sits INSIDE the boundary so the ramp cuts no more than the)')
w('(raster will. Its centre is one helix radius in from the start corner.)')
hr = HELIX_DIA / 2.0
w('#<hx> = [#<x0> + %.4f]' % hr)
w('G0 X#<hx> Y#<y0>')
turns = 3
for i in range(turns):
    z = Z_LAP - (Z_LAP - Z_FACE) * (i + 1) / float(turns)
    w('G3 X#<hx> Y#<y0> I-%.4f J0.0 Z%.4f F%.4f' % (hr, z, PLUNGE_FEED))
w('(one flat turn to clean the ramp out of the floor)')
w('G3 X#<hx> Y#<y0> I-%.4f J0.0 F%.4f' % (hr, FEED))
w('G1 X#<x0> Y#<y0> F%.4f' % FEED)
w()
w('(--- 5. raster along X, stepping %.4f in Y ---)' % STEP)
span = CENTRE_Y
npass = int(math.ceil(span / STEP)) + 1 if span > 0 else 1
w('(%d passes across %.4f mm of Y)' % (npass, span))
for i in range(npass):
    y = min(i * STEP, CENTRE_Y)
    if i % 2 == 0:
        w('G1 X#<x1> Y%.4f F%.4f' % (y, FEED))
    else:
        w('G1 X#<x0> Y%.4f F%.4f' % (y, FEED))
    if i < npass - 1:
        ynext = min((i + 1) * STEP, CENTRE_Y)
        w('G1 Y%.4f' % ynext)
w()
w('(--- 6. done ---)')
w('M5')
w('G0 Z%.4f' % Z_RAPID)
w('M30')
w('%')
print('\n'.join(L))
