#!/usr/bin/env python3
"""Counterbore grid for ned.

    tools/gen_cbore_grid.py > /home/brains/linuxcnc/nc_files/setup/cbore_grid_20.ngc

Operator 2026-09-29: "counterbores, 1/2in diamter, 1/2in deep. centered at 0,0
and the current position 1167 and 878. give me 4 equally spaced holes in Y and
5 in X. 1/4in bit (loaded) spindle 12000. chipload for mdf. rapids and
clearanced 5mm."

File shape is rule 3.6: title, PARAMETERS, DESCRIPTION, body.
"""
import math
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ngc_revision import revision_lines

# ---- the numbers the operator sets -----------------------------------------
X0, Y0      = 0.0, 0.0      # mm, the first hole
X1          = 1170.0        # mm, the last hole along X
# THE Y ROWS ARE THE BED'S OWN SLOT CENTRES, not an even pitch. Operator
# 2026-09-29: 'i want the hole pattern in Y to mimic the spacing from the
# tnut holes' ... 'that way im guaranteed that they will not intefere'.
# From docs/fixtures/BedTnutSlots.json, centre_pitch_y:
#     316.725, 250.725, 249.725, 249.725, 309.725
# uneven because it follows the plate widths -- his 'the first and last
# spacing are larger. the ones in middle smaller'. Six slots, six rows, so
# every bolt through a counterbore reaches a T-nut instead of hitting plate.
Y_ROWS      = [0.0, 316.725, 567.450, 817.175, 1066.900, 1376.625]
NX          = 5             # holes along X
NY          = len(Y_ROWS)
CB_DIA      = 12.7          # mm, 1/2 in counterbore
CB_DEPTH    = 12.7          # mm, 1/2 in deep
TOOL        = 12            # T12, the 1/4 in end mill, already loaded
TOOL_DIA    = 6.35          # mm, must match the tool table DIAMETER
FLUTES      = 2             # from the tool table
SPINDLE_RPM = 12000
CHIPLOAD    = 0.20          # mm/tooth, MDF with a 1/4 in carbide
Z_CLEAR     = 5.0           # mm, rapids and clearance
DOC         = 3.0           # mm of Z per orbit
DWELL       = 3.0           # s, spindle settle

FEED   = CHIPLOAD * SPINDLE_RPM * FLUTES
PLUNGE = FEED / 3.0
ORBIT  = (CB_DIA - TOOL_DIA) / 2.0
DX     = (X1 - X0) / (NX - 1)
TURNS  = int(math.ceil(CB_DEPTH / DOC))

L = []
def w(s=''):
    L.append(s)

w('%')
w('(CBORE GRID -- %d x %d = %d counterbores, %s dia x %s deep, T%d)'
  % (NX, NY, NX * NY, f'{CB_DIA:.1f}', f'{CB_DEPTH:.1f}', TOOL))
w('(GENERATED by ned:tools/gen_cbore_grid.py -- edit the generator, not this file)')
w('(STOCK TOP Z 0.)')
w()
w('(=== PARAMETERS -- set these before you run ============================)')
w('(  Change a number here and nothing else. Every move below reads them.)')
w('#<x0>       = %.4f      (mm, the first hole)' % X0)
w('#<y0>       = %.4f      (mm)' % Y0)
w('#<dx>       = %.4f    (mm, X pitch -- %d holes from %.1f to %.1f)'
  % (DX, NX, X0, X1))
for _i, _y in enumerate(Y_ROWS, 1):
    w('#<y%d>       = %9.4f   (mm, bed slot %d)' % (_i, _y, _i))
w('#<nx>       = %d           (holes along X)' % NX)
w('(  %d Y rows above -- the bed slot centres, uneven by design)' % NY)
w('#<orbit>    = %.4f      (mm, = [cbore %.1f - cutter %.2f] / 2)'
  % (ORBIT, CB_DIA, TOOL_DIA))
w('#<depth>    = %.4f     (mm, counterbore depth, NEGATIVE going down)' % CB_DEPTH)
w('#<doc>      = %.4f      (mm of Z per orbit)' % DOC)
w('#<tool>     = %d          (T%d, the 1/4 in end mill)' % (TOOL, TOOL))
w('#<tool_dia> = %.4f      (mm, must match the tool table DIAMETER)' % TOOL_DIA)
w('#<rpm>      = %d       (Vc = pi x %.2f x %d / 1000 = %.1f m/min)'
  % (SPINDLE_RPM, TOOL_DIA, SPINDLE_RPM, math.pi * TOOL_DIA * SPINDLE_RPM / 1000))
w('#<feed>     = %.4f   (mm/min, %.2f mm/tooth at %d flutes -- MDF)'
  % (FEED, CHIPLOAD, FLUTES))
w('#<plunge>   = %.4f   (mm/min, a third of the feed)' % PLUNGE)
w('#<clear>    = %.4f      (mm, rapids and clearance above Z0)' % Z_CLEAR)
w('#<dwell>    = %.4f      (s, spindle settle)' % DWELL)
w()
w('(=== DESCRIPTION -- what this does, in order ===========================)')
w('(  Z0 IS THE TOP OF THE WORK. You touch off there with T%d in the)' % TOOL)
w('(  holder. The file refuses unless that tool is still in the spindle and)')
w('(  unless a tool LENGTH is applied, because Z0 means nothing otherwise.)')
w('( )')
w('(  %d holes: %d along X at %.4f pitch, on %d Y rows taken from the BED)'
  % (NX * NY, NX, DX, NY))
w('(  SLOT CENTRES -- 316.725, 250.725, 249.725, 249.725, 309.725 -- so a)')
w('(  bolt through any counterbore reaches a T-nut rather than plate.)')
w('( )')
w('(  Each hole is a %s dia counterbore cut with a %s cutter, so the tool)'
  % (f'{CB_DIA:.1f}', f'{TOOL_DIA:.2f}'))
w('(  orbits at radius %.4f. It steps down %.1f per turn -- %d turns to)'
  % (ORBIT, DOC, TURNS))
w('(  reach Z-%.1f -- then one flat turn at depth to clean the floor.)'
  % CB_DEPTH)
w('( )')
w('(  Rule 4.5: machine Z0 first, then the start XY, then anything else.)')
w()
w('(=== BODY ==============================================================)')
w('G21 G90 G17 G94 G40 G49 G54')
w('G64 P0.01 Q0.01')
w()
w('o100 if [#5400 NE #<tool>]')
w('  (abort, CBORE GRID: that tool is not in the spindle - load it and declare it first)')
w('o100 endif')
w('o101 if [ABS[#5410 - #<tool_dia>] GT 0.01]')
w('  (abort, CBORE GRID: the tool in the spindle is not the diameter this file expects - check the tool table DIAMETER)')
w('o101 endif')
w('(THE TOOL LENGTH MUST BE IN FORCE. #5403 is the APPLIED offset, zeroed by)')
w('(G49. Loading a program resets the interpreter and re-runs the ini startup)')
w('(code, which contains G49 -- so opening this file after touching off drops)')
w('(the offset silently while the DRO still reads plausible numbers.)')
w('o102 if [ABS[#5403] LT 0.001]')
w('  (abort, CBORE GRID: no tool length is applied - G49 is in force so Z0 is the spindle nose - press G43, re-check your Z zero, then run)')
w('o102 endif')
w()
w('G53 G0 Z0')
w('G0 X#<x0> Y#<y0>')
w('M3 S#<rpm>')
w('G4 P#<dwell>')
w('G0 Z#<clear>')
w()
for _i in range(1, len(Y_ROWS) + 1):
    w('(--- row %d of %d, at the bed slot centre ---)' % (_i, len(Y_ROWS)))
    w('#<yy>  = #<y%d>' % _i)
    w('#<jx>  = 0')
    w('o%d0 while [#<jx> LT #<nx>]' % (20 + _i))
    w('  #<xx> = [#<x0> + #<jx> * #<dx>]')
    w('  G0 Z#<clear>')
    w('  G0 X#<xx> Y#<yy>')
    w('  G1 X[#<xx> + #<orbit>] F#<feed>')
    w('  #<zz> = 0')
    w('  o%d1 while [#<zz> GT [0 - #<depth>]]' % (20 + _i))
    w('    #<zz> = [#<zz> - #<doc>]')
    w('    o%d2 if [#<zz> LT [0 - #<depth>]]' % (20 + _i))
    w('      #<zz> = [0 - #<depth>]')
    w('    o%d2 endif' % (20 + _i))
    w('    G3 X[#<xx> + #<orbit>] Y#<yy> I-#<orbit> J0.0 Z#<zz> F#<plunge>')
    w('  o%d1 endwhile' % (20 + _i))
    w('  G3 X[#<xx> + #<orbit>] Y#<yy> I-#<orbit> J0.0 F#<feed>')
    w('  G1 X#<xx> F#<feed>')
    w('  G0 Z#<clear>')
    w('  #<jx> = [#<jx> + 1]')
    w('o%d0 endwhile' % (20 + _i))
    w()

w()
w('M5')
w('G53 G0 Z0')
w('M30')
w('%')

CHANGED = ('%d x %d holes, X %.1f to %.1f, Y on the BED SLOT CENTRES '
           '%.1f to %.1f, %s dia x %s deep'
           % (NX, NY, X0, X1, Y_ROWS[0], Y_ROWS[-1],
              f'{CB_DIA:.1f}', f'{CB_DEPTH:.1f}'))
_hdr = revision_lines(L[1:], 'gen_cbore_grid.py', CHANGED)
print('\n'.join([L[0]] + _hdr + L[1:]))
