#!/usr/bin/env python3
"""Generate the bed facing program for ned.

    tools/gen_facing.py > /home/brains/linuxcnc/nc_files/setup/face_bed.ngc

FILE SHAPE, operator 2026-09-29: "i want it to follow all the rules, have
parameters i can set right away second, and a clear description of the code
after that before the code body."  So: title, PARAMETERS, DESCRIPTION, body.

THE CONFIDENCE LAP, operator 2026-09-29: "THE FIRST THING YOU DO IS TO MOVE
ALONG THE OUTER PATH AT Z5. THIS GIVES ME CONFIDENCE THAT I AM FACING
EVERYTHING BEFORE IT THEN PROCEEDS TO THE FACING."  One lap of the rectangle
at Z5, cutting nothing, before anything goes down.
"""
import math
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ngc_revision import revision_lines

# ---- the numbers the operator sets -----------------------------------------
# THE TOOL CENTRE PATH, not the cut boundary. Operator 2026-09-29: 'TOOL
# CENTER FROM Y = 0 TO 1500 WILL DO'. The cutter EDGE therefore overhangs
# by one radius on every side, so the swept surface is R bigger all round.
START_X     = -75.0    # mm, operator 2026-09-29: 'make it start from
                       # x=-75'. The cut begins here, not at X0
CENTRE_X    = 2570.0   # mm, centre travels START_X -> here. 4043.725 available
CENTRE_Y    = 1500.0   # mm, centre travels Y0 -> Y1500. 1788.000 available
TOOL        = 1        # T1, the 3 in face mill
TOOL_DIA    = 76.2     # mm, must match the tool table DIAMETER
OVERLAP     = 12.7     # mm, 0.5 in. Operator 2026-09-29: '.5in overlap
                       # should do'. STEPOVER is derived: dia - overlap
SPINDLE_RPM = 5000     # operator 2026-09-29: 'LETS RUN IT AT 5000 rpm.
                       # that should be plenty for this 3in face mill.'
                       # Vc = pi * 76.2 * 5000 / 1000 = 1197 m/min
FEED        = 6000.0   # mm/min = 0.200 mm/tooth at 6 flutes and 5000 rpm.
                       # DERIVED from the rpm to hold the chip load -- raising
                       # S without F would have thinned it to 0.160
PLUNGE_FEED = 600.0    # mm/min, the helix
Z_RAPID     = 10.0     # mm, the height every rapid runs at
Z_LAP       = 5.0      # mm, the confidence lap
Z_FACE      = 0.0      # mm, the finished surface. The operator zeroes here
HELIX_DIA   = 76.2     # mm, 3 in, one cutter diameter
DWELL       = 3.0      # s, spindle settle before the first move
CHANGED     = 'X now starts at -75.0 instead of 0'   # rule 3.7, one line

R = TOOL_DIA / 2.0
STEP = TOOL_DIA - OVERLAP
L = []
def w(s=''):
    L.append(s)

w('%')
w('(FACE BED -- %s x %s mm, T%d %s mm face mill)'
  % (f'{CENTRE_X:.1f}', f'{CENTRE_Y:.1f}', TOOL, f'{TOOL_DIA:.1f}'))
w('(GENERATED by ned:tools/gen_facing.py -- edit the generator, not this file)')
w()
w('(=== PARAMETERS -- set these before you run ============================)')
w('(  Change a number here and nothing else. Every move below is built from)')
w('(  these, so the file stays true to whatever you set.)')
w('#<start_x>    = %.4f    (mm, the TOOL CENTRE starts here, not at X0)' % START_X)
w('#<centre_x>   = %.4f   (mm, and runs to here. 4043.725 of travel)' % CENTRE_X)
w('#<centre_y>   = %.4f   (mm, the TOOL CENTRE runs Y0 to here. 1788.000 -- the tight one)' % CENTRE_Y)
w('#<tool>       = %d        (T%d, the 3 in face mill)' % (TOOL, TOOL))
w('#<tool_dia>   = %.4f     (mm, must match the tool table DIAMETER)' % TOOL_DIA)
w('#<stepover>   = %.4f     (mm, = dia %.1f minus %.1f overlap)' % (STEP, TOOL_DIA, OVERLAP))
w('#<rpm>        = %d        (Vc = pi x dia x rpm / 1000 = %.0f m/min)'
  % (SPINDLE_RPM, math.pi * TOOL_DIA * SPINDLE_RPM / 1000.0))
w('#<feed>       = %.4f   (mm/min, %.4f mm/tooth at 6 flutes)'
  % (FEED, FEED / (SPINDLE_RPM * 6.0)))
w('#<plunge>     = %.4f    (mm/min, the descent to the face)' % PLUNGE_FEED)
w('#<z_rapid>    = %.4f     (mm, every rapid runs at this height)' % Z_RAPID)
w('#<z_face>     = %.4f      (mm, the finished surface. You zero here)' % Z_FACE)
w('#<dwell>      = %.4f      (s, spindle settle before the first move)' % DWELL)
w()
w('(=== DESCRIPTION -- what this does, in order ===========================)')
w('(  Z0 IS THE FINISHED SURFACE. You touch off on where you want the bed)')
w('(  to END UP, with T%d already in the holder. The program never asks how)' % TOOL)
w('(  much stock is above that -- it faces to Z0 and stops.)')
w('( )')
w('(  The TOOL CENTRE starts at X%s Y0 and runs to X%s Y%s. The edge)'
  % (f'{START_X:.1f}', f'{CENTRE_X:.1f}', f'{CENTRE_Y:.1f}'))
w('(  overhangs %.4f all round, so the surface actually swept is)' % R)
w('(  X%.4f to X%.4f by Y%.4f to Y%.4f.)'
  % (START_X - R, CENTRE_X + R, -R, CENTRE_Y + R))
w('( )')
w('(  1. REFUSE unless T%d is actually in the spindle and its diameter)' % TOOL)
w('(     matches. Z0 means nothing if a different cutter touched it off.)')
w('(  2. MACHINE Z0 first, then the start XY, then down to Z%s. Spindle)'
  % f'{Z_RAPID:.1f}')
w('(     on, %d rpm, %s s settle.)' % (SPINDLE_RPM, f'{DWELL:.0f}'))
w('(  3. The confidence lap is COMMENTED OUT. Five ; lines, uncomment to)')
w('(     get it back. It was one full circuit of the rectangle at Z%s,)' % f'{Z_LAP:.1f}')
w('(     cutting nothing, so you can watch the whole boundary go past before)')
w('(     anything descends. Operator 2026-09-29: "THIS GIVES ME CONFIDENCE)')
w('(     THAT I AM FACING EVERYTHING BEFORE IT THEN PROCEEDS TO THE FACING".)')
w('(     The lap traces the CUTTER CENTRE path -- X0 Y0 to X%s Y%s --)'
  % (f'{CENTRE_X:.1f}', f'{CENTRE_Y:.1f}'))
w('(     so the cutter EDGE runs %.4f outside it on every side.)' % R)
w('(  4. Straight descent to Z%s at the plunge feed, at the start corner.)'
  % f'{Z_FACE:.1f}')
w('(  5. %d passes, EVERY ONE CUTTING IN +X, stepping %.4f in Y. The return)'
  % (int(math.ceil(CENTRE_Y / STEP)) + 1, STEP))
w('(     is a rapid at Z%s, clear of the surface.)' % f'{Z_RAPID:.1f}')
w('(  6. Spindle off, Z clear. It does not return anywhere -- you decide.)')
w()
w('(=== BODY ==============================================================)')
w('(Every move below reads the PARAMETERS block. Nothing here is a literal)')
w('(that duplicates a number up there -- change it once, at the top, and the)')
w('(whole program follows. On 2026-09-29 the first version of this file had)')
w('(a parameter block over a body of literals: the operator changed centre_x)')
w('(to 2570 and the machine would still have run 2470. A parameter that does)')
w('(not drive anything is worse than none -- it reads as a guarantee.)')
w('G21 G90 G17 G94 G40 G49 G54')
w('G64 P0.05 Q0.05')
w()
w('(No tool change and no G43. Z0 was touched off with this cutter already)')
w('(in the holder, so the file refuses unless that is still true.)')
w('o100 if [#5400 NE #<tool>]')
w('  (abort, FACE BED: that tool is not in the spindle - load it and declare it first)')
w('o100 endif')
w('o101 if [ABS[#5410 - #<tool_dia>] GT 0.01]')
w('  (abort, FACE BED: the tool in the spindle is not the diameter this file expects - check the tool table DIAMETER)')
w('o101 endif')
w()
w('(THE TOOL LENGTH MUST BE IN FORCE. #5401-#5409 are the APPLIED offsets --)')
w('(set by the G43 family, zeroed by G49 -- so #5403 EQ 0 means the machine)')
w('(is positioning the SPINDLE NOSE, not the tip. Z0 was touched off with)')
w('(the tip, so every move would run one whole tool length deeper.)')
w('(2026-09-29: LOADING A PROGRAM RESETS THE INTERPRETER, which re-runs)')
w('(RS274NGC_STARTUP_CODE, and that line contains G49. So opening this file)')
w('(after touching off silently drops the offset, and the DRO still reads a)')
w('(plausible number. Nothing else on this machine catches it.)')
w('o102 if [ABS[#5403] LT 0.001]')
w('  (abort, FACE BED: no tool length is applied - G49 is in force so Z0 is the spindle nose and the tip would run one tool length deeper - press G43, re-check your Z zero, then run)')
w('o102 endif')
w()
w('(THE TOOL CENTRE PATH. Not inset -- these ARE the parameters above. The)')
w('(cutter EDGE overhangs by one radius on every side.)')
w('#<x0> = #<start_x>')
w('#<y0> = 0.0000')
w('#<x1> = #<centre_x>')
w('#<y1> = #<centre_y>')
w('o103 if [[#<x1> LE #<x0>] OR [#<y1> LE #<y0>]]')
w('  (abort, FACE BED: centre_x and centre_y must both be greater than zero)')
w('o103 endif')
w('o104 if [#<stepover> LE 0]')
w('  (abort, FACE BED: stepover must be greater than zero)')
w('o104 endif')
w()
w('(MACHINE Z0 FIRST, THEN THE START XY, THEN ANYTHING ELSE. Operator)')
w('(2026-09-29: "whenever going to start of path. it MUST always, go to)')
w('(mscZ0, go to start XY. then do wahtever after that". G53 Z0 is the top)')
w('(of Z travel and is the ONE height where no XY move can strike anything)')
w('(-- a work-frame retract is only as safe as the offset it is measured)')
w('(from, and that offset is exactly what goes wrong.)')
w('G53 G0 Z0')
w('G0 X#<x0> Y#<y0>')
w('(RULE 6.3: THE SPINDLE STARTS HERE, AT THE XY RESUME, AND THE DESCENT)')
w('(COMES AFTER THE DWELL. I had the Z rapid above the M3 and the operator)')
w('(caught it: "did you break the spindle spinup rule as well". A cutter)')
w('(that spins up while already down is a cutter spinning in the work.)')
w('M3 S#<rpm>')
w('G4 P#<dwell>')
w('G0 Z#<z_rapid>')
w()
w('(--- 3. THE CONFIDENCE LAP -- COMMENTED OUT, operator 2026-09-29: ---)')
w('(    "comment out the outside parameter move". Uncomment the five lines)')
w('(    below to get it back: it runs the whole boundary at z_lap, cutting)')
w('(    nothing, so the full extent can be watched before anything descends.)')
w('; G0 Z%.4f' % Z_LAP)
w('; G1 X#<x1> Y#<y0> F#<feed>')
w('; G1 X#<x1> Y#<y1>')
w('; G1 X#<x0> Y#<y1>')
w('; G1 X#<x0> Y#<y0>')
w()
w('(--- 4. descend to the face. Operator 2026-09-29: "remove the helical ---)')
w('(    entry". Straight down at the plunge feed, at the start corner.)')
w('G0 Z#<z_rapid>')
w('G0 X#<x0> Y#<y0>')
w('G1 Z#<z_face> F#<plunge>')
w()
w('(--- 5. ONE DIRECTION ONLY, operator 2026-09-29: "make the cuts go ---)')
w('(    from one direction only instead of a zigzag". Every pass cuts in +X)')
w('(    so the cutter engages the same way every time -- a zig-zag alternates)')
w('(    climb and conventional and leaves a different finish on every other)')
w('(    stripe. The return is a rapid at z_rapid, clear of the surface.)')
w('#<yy>   = #<y0>')
w('#<more> = 1')
w('o120 while [#<more> GT 0]')
w('  G1 X#<x1> Y#<yy> F#<feed>')
w('  G0 Z#<z_rapid>')
w('  o122 if [#<yy> GE #<y1>]')
w('    #<more> = 0')
w('  o122 else')
w('    #<yy> = [#<yy> + #<stepover>]')
w('    o123 if [#<yy> GT #<y1>]')
w('      #<yy> = #<y1>')
w('    o123 endif')
w('    G0 X#<x0> Y#<yy>')
w('    G1 Z#<z_face> F#<plunge>')
w('  o122 endif')
w('o120 endwhile')
w()
w('(--- 6. done ---)')
w('M5')
w('G0 Z#<z_rapid>')
w('M30')
w('%')
# RULE 3.7: the revision header goes on top, and its md5 is of everything
# below it -- computed last, inserted first.
_hdr = revision_lines(L[1:], 'gen_facing.py', CHANGED)
print('\n'.join([L[0]] + _hdr + L[1:]))
