#!/usr/bin/env python3
"""Counterbore grid for ned.

    tools/gen_cbore_grid.py > /home/brains/linuxcnc/nc_files/setup/cbore_grid_20.ngc

Operator 2026-09-29: "counterbores, 1/2in diamter, 1/2in deep. centered at 0,0
and the current position 1167 and 878. give me 4 equally spaced holes in Y and
5 in X. 1/4in bit (loaded) spindle 12000. chipload for mdf. rapids and
clearanced 5mm."

File shape is rule 3.6: title, PARAMETERS, DESCRIPTION, body.
"""
import math
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ngc_revision import revision_lines

# ---- the numbers the operator sets -----------------------------------------
X0, Y0      = 0.0, 0.0      # mm, the first hole
X1, Y1      = 1170.0, 1500.0 # mm, the last hole. Operator 2026-09-29:
                            # 'Y space 1500, X span 1200'
NX, NY      = 5, 6          # 'holes in X 5, holes in Y 6'
CB_DIA      = 12.7          # mm, 1/2 in counterbore
CB_DEPTH    = 12.7          # mm, 1/2 in deep
TOOL        = 12            # T12, the 1/4 in end mill, already loaded
TOOL_DIA    = 6.35          # mm, must match the tool table DIAMETER
FLUTES      = 2             # from the tool table
SPINDLE_RPM = 12000
CHIPLOAD    = 0.20          # mm/tooth, MDF with a 1/4 in carbide
Z_CLEAR     = 5.0           # mm, rapids and clearance
DOC         = 3.0           # mm of Z per orbit
DWELL       = 3.0           # s, spindle settle

FEED   = CHIPLOAD * SPINDLE_RPM * FLUTES
PLUNGE = FEED / 3.0
ORBIT  = (CB_DIA - TOOL_DIA) / 2.0
DX     = (X1 - X0) / (NX - 1)
DY     = (Y1 - Y0) / (NY - 1)
TURNS  = int(math.ceil(CB_DEPTH / DOC))

L = []
def w(s=''):
    L.append(s)

w('%')
w('(CBORE GRID -- %d x %d = %d counterbores, %s dia x %s deep, T%d)'
  % (NX, NY, NX * NY, f'{CB_DIA:.1f}', f'{CB_DEPTH:.1f}', TOOL))
w('(GENERATED by ned:tools/gen_cbore_grid.py -- edit the generator, not this file)')
w('(STOCK TOP Z 0.)')
w()
w('(=== PARAMETERS -- set these before you run ============================)')
w('(  Change a number here and nothing else. Every move below reads them.)')
w('#<x0>       = %.4f      (mm, the first hole)' % X0)
w('#<y0>       = %.4f      (mm)' % Y0)
w('#<dx>       = %.4f    (mm, X pitch -- %d holes from %.1f to %.1f)'
  % (DX, NX, X0, X1))
w('#<dy>       = %.4f    (mm, Y pitch -- %d holes from %.1f to %.1f)'
  % (DY, NY, Y0, Y1))
w('#<nx>       = %d           (holes along X)' % NX)
w('#<ny>       = %d           (holes along Y)' % NY)
w('#<orbit>    = %.4f      (mm, = [cbore %.1f - cutter %.2f] / 2)'
  % (ORBIT, CB_DIA, TOOL_DIA))
w('#<depth>    = %.4f     (mm, counterbore depth, NEGATIVE going down)' % CB_DEPTH)
w('#<doc>      = %.4f      (mm of Z per orbit)' % DOC)
w('#<tool>     = %d          (T%d, the 1/4 in end mill)' % (TOOL, TOOL))
w('#<tool_dia> = %.4f      (mm, must match the tool table DIAMETER)' % TOOL_DIA)
w('#<rpm>      = %d       (Vc = pi x %.2f x %d / 1000 = %.1f m/min)'
  % (SPINDLE_RPM, TOOL_DIA, SPINDLE_RPM, math.pi * TOOL_DIA * SPINDLE_RPM / 1000))
w('#<feed>     = %.4f   (mm/min, %.2f mm/tooth at %d flutes -- MDF)'
  % (FEED, CHIPLOAD, FLUTES))
w('#<plunge>   = %.4f   (mm/min, a third of the feed)' % PLUNGE)
w('#<clear>    = %.4f      (mm, rapids and clearance above Z0)' % Z_CLEAR)
w('#<dwell>    = %.4f      (s, spindle settle)' % DWELL)
w()
w('(=== DESCRIPTION -- what this does, in order ===========================)')
w('(  Z0 IS THE TOP OF THE WORK. You touch off there with T%d in the)' % TOOL)
w('(  holder. The file refuses unless that tool is still in the spindle and)')
w('(  unless a tool LENGTH is applied, because Z0 means nothing otherwise.)')
w('( )')
w('(  %d holes: %d along X at %.4f pitch, %d along Y at %.4f pitch, from)'
  % (NX * NY, NX, DX, NY, DY))
w('(  X%.1f Y%.1f to X%.1f Y%.1f. Column by column, X innermost.)'
  % (X0, Y0, X1, Y1))
w('( )')
w('(  Each hole is a %s dia counterbore cut with a %s cutter, so the tool)'
  % (f'{CB_DIA:.1f}', f'{TOOL_DIA:.2f}'))
w('(  orbits at radius %.4f. It steps down %.1f per turn -- %d turns to)'
  % (ORBIT, DOC, TURNS))
w('(  reach Z-%.1f -- then one flat turn at depth to clean the floor.)'
  % CB_DEPTH)
w('( )')
w('(  Rule 4.5: machine Z0 first, then the start XY, then anything else.)')
w()
w('(=== BODY ==============================================================)')
w('G21 G90 G17 G94 G40 G49 G54')
w('G64 P0.01 Q0.01')
w()
w('o100 if [#5400 NE #<tool>]')
w('  (abort, CBORE GRID: that tool is not in the spindle - load it and declare it first)')
w('o100 endif')
w('o101 if [ABS[#5410 - #<tool_dia>] GT 0.01]')
w('  (abort, CBORE GRID: the tool in the spindle is not the diameter this file expects - check the tool table DIAMETER)')
w('o101 endif')
w('(THE TOOL LENGTH MUST BE IN FORCE. #5403 is the APPLIED offset, zeroed by)')
w('(G49. Loading a program resets the interpreter and re-runs the ini startup)')
w('(code, which contains G49 -- so opening this file after touching off drops)')
w('(the offset silently while the DRO still reads plausible numbers.)')
w('o102 if [ABS[#5403] LT 0.001]')
w('  (abort, CBORE GRID: no tool length is applied - G49 is in force so Z0 is the spindle nose - press G43, re-check your Z zero, then run)')
w('o102 endif')
w()
w('G53 G0 Z0')
w('G0 X#<x0> Y#<y0>')
w('M3 S#<rpm>')
w('G4 P#<dwell>')
w('G0 Z#<clear>')
w()
w('#<jy> = 0')
w('o110 while [#<jy> LT #<ny>]')
w('  #<yy> = [#<y0> + #<jy> * #<dy>]')
w('  #<jx> = 0')
w('  o120 while [#<jx> LT #<nx>]')
w('    #<xx> = [#<x0> + #<jx> * #<dx>]')
w('    G0 Z#<clear>')
w('    G0 X#<xx> Y#<yy>')
w('    (move out to the orbit radius at the clearance height, then spiral down)')
w('    G1 X[#<xx> + #<orbit>] F#<feed>')
w('    #<zz> = 0')
w('    o130 while [#<zz> GT [0 - #<depth>]]')
w('      #<zz> = [#<zz> - #<doc>]')
w('      o131 if [#<zz> LT [0 - #<depth>]]')
w('        #<zz> = [0 - #<depth>]')
w('      o131 endif')
w('      G3 X[#<xx> + #<orbit>] Y#<yy> I-#<orbit> J0.0 Z#<zz> F#<plunge>')
w('    o130 endwhile')
w('    (one flat turn at depth to clean the floor)')
w('    G3 X[#<xx> + #<orbit>] Y#<yy> I-#<orbit> J0.0 F#<feed>')
w('    G1 X#<xx> F#<feed>')
w('    G0 Z#<clear>')
w('    #<jx> = [#<jx> + 1]')
w('  o120 endwhile')
w('  #<jy> = [#<jy> + 1]')
w('o110 endwhile')
w()
w('M5')
w('G53 G0 Z0')
w('M30')
w('%')

CHANGED = ('new: %d x %d counterbore grid, %s dia x %s deep, T%d at S%d'
           % (NX, NY, f'{CB_DIA:.1f}', f'{CB_DEPTH:.1f}', TOOL, SPINDLE_RPM))
_hdr = revision_lines(L[1:], 'gen_cbore_grid.py', CHANGED)
print('\n'.join([L[0]] + _hdr + L[1:]))
