#!/bin/bash
# run5.sh -- launch the machine under PROBE BASIC (configs/ned5_pb/ned5_pb.ini)
# with FULL output capture, so Claude can self-monitor and NEVER needs anything
# pasted from the terminal.
#
#   LinuxCNC + Probe Basic stdout/stderr (startup errors, tracebacks, runtime)
#       -> ned/lcnc.log
#   Machine events (head reads, homing verify, resume arming, teleop, programs)
#       -> ned/gui.md          (written by tools/live/ned_brain.py)
#   Mesa pin states
#       -> ned/mesa.log        (tools/live/mesalog.sh)
#
# Launch the machine with:   ned/tools/run5.sh
# Launch WITHOUT re-homing XYZ:   ned/tools/run5.sh resume     (machine must NOT
#   have been moved since the last homed session). Consent happens HERE, before
#   launch: the stored positions are shown and you must type y. ned_brain then
#   arms ini.0-3.home/home_offset at startup; HOME ALL homes joints 0-3 IN
#   PLACE at those values with zero motion. A/C still do their normal absolute
#   read -> home -> verify (ned_brain).
# Then just tell Claude "I did X" -- Claude reads lcnc.log / gui.md / mesa.log.
#
# probe_basic + qtpyvcp live in the qt_pb venv -> put it on PATH first
# (a plain `linuxcnc ned5_pb.ini` from a non-login shell will NOT find them).

NED="/home/brains/Documents/ned"
INI="$NED/configs/ned5_pb/ned5_pb.ini"
LOG="$NED/lcnc.log"
VENV="$HOME/qt_pb/qtpyvcp/venv"

if [ ! -x "$VENV/bin/probe_basic" ]; then
  echo "run5: probe_basic not found in $VENV -- see tools/live/qt_pb.sh +"
  echo "      docs/commissioning/probe_basic_migration.md (cmake/PySide6/vtk)"; exit 1
fi
# shellcheck disable=SC1091
source "$VENV/bin/activate"

# `resume` -> stored homing. HOME_SEARCH_VEL is config-time only (inihal exposes
# just home/home_offset/home_sequence at runtime), so skipping the switch search
# REQUIRES a different ini: generate one whose [JOINT_0..3] home IN PLACE
# (search/latch vel 0 -> homing.c:807 immediate path). Overrides sit between the
# section header and the #INCLUDE line (IniFile::Find returns the FIRST match).
# The nedgui confirmation dialog is gone -- consent is THIS prompt; ned_brain
# refuses to arm without NED_RESUME_OK=1 and aborts any un-armed homing attempt.
if [ "${1:-}" = "resume" ]; then
  SH="$NED/configs/ned5/stored_home.json"
  if [ ! -r "$SH" ]; then echo "run5: resume refused -- $SH missing"; exit 1; fi
  echo "run5: RESUME -- joints 0-3 will be declared homed AT (no motion):"
  python3 - "$SH" <<'EOF'
import json, sys
d = json.load(open(sys.argv[1]))
j = d['joints']
print('      saved {}   X {:+.3f}   Y {:+.3f}   Z {:+.3f}   X2 {:+.3f}'.format(
    d.get('saved', '?'), j['0'], j['1'], j['2'], j['3']))
EOF
  echo "      ONLY if the machine has NOT been moved since then."
  read -r -p "run5: proceed? [y/N] " ok
  [ "$ok" = "y" ] || { echo "run5: resume declined"; exit 1; }
  export NED_RESUME_OK=1
  GEN="$NED/configs/ned5_pb/ned5_pb_resume_gen.ini"
  awk '{
    print
    if ($0 ~ /^\[JOINT_[0-3]\]$/) {
      print "# RESUME overrides (generated by run5.sh resume -- do not hand-edit; first-match-wins"
      print "# shadows the #INCLUDE values below): home IN PLACE at ini.N.home_offset, no motion."
      print "HOME_SEARCH_VEL = 0"
      print "HOME_LATCH_VEL = 0"
      print "HOME_USE_INDEX = NO"
    }
  }' "$INI" > "$GEN" || { echo "run5: resume ini generation FAILED"; exit 1; }
  INI="$GEN"
  echo "run5: RESUME mode -- ned_brain arms the stored positions at startup"
fi

# cores ON: rtapi_app said "dumping core" on the 2026-07-31 SIGSEGV but ulimit -c
# was 0, so there was no core to autopsy. Next time there will be.
ulimit -c unlimited 2>/dev/null || true

# SOFTWARE GL for the VTK backplot: TRIED AND REMOVED (2026-08-01) --
# llvmpipe ground >5 min at 95% CPU during VTK init on this Pi ("pb isnt
# even loading"). Backplot stays invisible (V3D = GL 3.1 < VTK's 3.2)
# until a lighter path is found. Do NOT re-add LIBGL_ALWAYS_SOFTWARE=1.

# 1. clear any stale realtime so the start is always clean (blocks the "won't start")
halrun -U >/dev/null 2>&1 || true

# announce who is using the machine

# 2. ensure the Mesa pin logger + log pruner are running
pgrep -f 'tools/live/mesalog.sh' >/dev/null 2>&1 || ( "$NED/tools/live/mesalog.sh" >/dev/null 2>&1 & )
pgrep -f 'tools/live/logclean.sh' >/dev/null 2>&1 || ( "$NED/tools/live/logclean.sh" >/dev/null 2>&1 & )

# 3. keep lcnc.log bounded (last ~2000 lines) + stamp a session header
if [ -f "$LOG" ]; then tail -n 2000 "$LOG" > "$LOG.tmp" 2>/dev/null && mv "$LOG.tmp" "$LOG"; fi
{ echo; echo "==================== LinuxCNC start (PROBE BASIC)  $(date '+%F %T') ===================="; } >> "$LOG"

# 4. launch under `script` so LinuxCNC sees a TTY. Without one, /usr/bin/linuxcnc:203
# pops a modal wish dialog on error and BLOCKS; with a pty the error is printed
# and captured here instead.
script -q -a -c "linuxcnc '$INI'" "$LOG"
